// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnnn2qG7aDE2oy7gdxAKgHYcnphehZ0nU',
    appId: '1:550432099354:web:04d809c0cd65e77bfd55a3',
    messagingSenderId: '550432099354',
    projectId: 'qr-response',
    authDomain: 'qr-response.firebaseapp.com',
    storageBucket: 'qr-response.firebasestorage.app',
    measurementId: 'G-6WW6Q7LVQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlkHxEcGOM1xyK2vRpP01egqby-6hOru8',
    appId: '1:550432099354:android:c657a6e8c1104486fd55a3',
    messagingSenderId: '550432099354',
    projectId: 'qr-response',
    storageBucket: 'qr-response.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zSrpKjOl0Kawo-cDdJDsr0wHFe2_bSQ',
    appId: '1:550432099354:ios:0b359bd4e3ee6c78fd55a3',
    messagingSenderId: '550432099354',
    projectId: 'qr-response',
    storageBucket: 'qr-response.firebasestorage.app',
    iosBundleId: 'com.example.sihApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zSrpKjOl0Kawo-cDdJDsr0wHFe2_bSQ',
    appId: '1:550432099354:ios:0b359bd4e3ee6c78fd55a3',
    messagingSenderId: '550432099354',
    projectId: 'qr-response',
    storageBucket: 'qr-response.firebasestorage.app',
    iosBundleId: 'com.example.sihApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnnn2qG7aDE2oy7gdxAKgHYcnphehZ0nU',
    appId: '1:550432099354:web:43e095170637125dfd55a3',
    messagingSenderId: '550432099354',
    projectId: 'qr-response',
    authDomain: 'qr-response.firebaseapp.com',
    storageBucket: 'qr-response.firebasestorage.app',
    measurementId: 'G-43QJVTXFXW',
  );

}